
// Generated by @bacons/apple-targets via the appIntents option in the config file.
import AppIntents
import SwiftUI
import WidgetKit

// TODO: These must be added to the WidgetBundle manually. They need to be linked outside of the _shared folder.
// @main
// struct exportWidgets: WidgetBundle {
//     var body: some Widget {
//         widgetControl0()
//         widgetControl1()
//     }
// }

@available(iOS 18.0, *)
struct widgetControl0: ControlWidget {
    static let kind: String = "com.bacon.clipdemo.0"
    var body: some ControlWidgetConfiguration {
      StaticControlConfiguration(kind: Self.kind) {
        ControlWidgetButton(action: OpenAppIntent0()) {
          Label("Bacon", systemImage: "laurel.leading")
        }
      }
      .displayName("Launch Bacon")
      .description("A an OPEN BACON control that runs a timer.")
    }
}

// This must be in both targets when `openAppWhenRun = true`
// https://developer.apple.com/forums/thread/763851
@available(iOS 18.0, *)
struct OpenAppIntent0: ControlConfigurationIntent {
    static let title: LocalizedStringResource = "Launch Bacon"
    static let description = IntentDescription(stringLiteral: "A an OPEN BACON control that runs a timer.")
    static let isDiscoverable = true
    static let openAppWhenRun: Bool = true
    
    @MainActor
    func perform() async throws -> some IntentResult & OpensIntent {
        return .result(opensIntent: OpenURLIntent(URL(string: "https://pillarvalley.netlify.app/settings")!))
    }
}

@available(iOS 18.0, *)
struct widgetControl1: ControlWidget {
    static let kind: String = "com.bacon.clipdemo.1"
    var body: some ControlWidgetConfiguration {
      StaticControlConfiguration(kind: Self.kind) {
        ControlWidgetButton(action: OpenAppIntent1()) {
          Label("Expo", systemImage: "laurel.trailing")
        }
      }
      .displayName("Launch Eggs")
      .description("A control that launches eggs.")
    }
}

// This must be in both targets when `openAppWhenRun = true`
// https://developer.apple.com/forums/thread/763851
@available(iOS 18.0, *)
struct OpenAppIntent1: ControlConfigurationIntent {
    static let title: LocalizedStringResource = "Launch Eggs"
    static let description = IntentDescription(stringLiteral: "A control that launches eggs.")
    static let isDiscoverable = true
    static let openAppWhenRun: Bool = true
    
    @MainActor
    func perform() async throws -> some IntentResult & OpensIntent {
        return .result(opensIntent: OpenURLIntent(URL(string: "https://expo.dev")!))
    }
}
      